<?php 
/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */



function reason_for_cancellation__get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function reason_for_cancellation__add_meta_box() {
	add_meta_box(
		'reason_for_cancellation_-reason-for-cancellation',
		__( 'Reason for Rejection?', 'reason_for_cancellation_' ),
		'reason_for_cancellation__html',
		'directories',
		'side',
		'high'
	);
	add_meta_box(
		'meta_data_fields',
		__( 'Post Fields', 'meta_data_fields' ),
		'meta_data_fields_html',
		'directories',
		'normal',
		'high'
	);
	add_meta_box(
		'reason_for_cancellation_data',
		__( 'Request for update', 'reason_for_cancellation_data' ),
		'reason_for_cancellation_data_html',
		'directories',
		'normal',
		'low'
	);
	add_meta_box(
		'gallery_images_first',
		__( 'Images', 'gallery_images_first' ),
		'gallery_images_first',
		'directories',
		'normal',
		'low'
	);
}
add_action( 'add_meta_boxes', 'reason_for_cancellation__add_meta_box' );

function gallery_images_first(){
	require 'cs_images.php';
}
function reason_for_cancellation_data_html(){
	require 'cs_update_data.php';
}



function meta_data_fields_html(){
	require 'meta_data_fields_html.php';
	// echo "string";
}


function reason_for_cancellation__html( $post) {
	wp_nonce_field( '_reason_for_cancellation__nonce', 'reason_for_cancellation__nonce' ); ?>

<input type="text" name="reason_for_cancellation__reason" id="reason_for_cancellation__reason" value="<?php echo reason_for_cancellation__get_meta( 'reason_for_cancellation__reason' ); ?>">
<?php
}

function reason_for_cancellation__save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['reason_for_cancellation__nonce'] ) || ! wp_verify_nonce( $_POST['reason_for_cancellation__nonce'], '_reason_for_cancellation__nonce' ) ) return;

	$post = get_post($post_id);
	if ($post->post_status == 'publish') {

		if (!empty($_POST['images'])) {
			foreach ($_POST['images'] as $key => $value) {
				global $wpdb;
				$wpdb->update( $wpdb->prefix.'post_images', ['adminPendingApprove' => 1, 'isDelete' => 0, ], ['id' => $value ]);
			}
		}
	
	$headers = "MIME-Version: 1.0" . "\r\n";
	$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
	wp_mail( get_user_email_by_id($post->post_author),'ECONDIR | Profile Approved', '<table style="width: 610px; background-color: #fff; display: table; margin: auto;">
	<tbody>
        <tr>
        <td>
            <table style="width: 563px; display: table; margin: 20px auto 0; background-color: #2a2a2a;">
                <tbody>
                    <tr>
                    <td style="width: 50%;  padding: 10px 0 10px 10px;"><a href="index.html"><img style="display: table; margin: 50px auto 50px;" src="http://dev17.onlinetestingserver.com/hn/econdir-wp/wp-content/themes/econ-dir/images/logo.png"></a></td>
                    </tr>
                </tbody>
            </table>

            <table style="width: 563px; display: table; margin: auto; background-color: #f2f2f2;">
                <tbody>
                    <tr>
                    <td style="padding: 70px 0px 70px 0;">
                
                        <p style="font-size: 16px; color: #4d4d4d; font-family: Gotham, Helvetica Neue, Helvetica, Arial, sans-serif; text-align: center; padding: 0 50px 0 50px; margin: 0 0 0 0; line-height: 30px;">Dear User,<br>

                          Congratulation! your profile has been approved. <br>
<br>


Have a great day!
<br>
<br>


Best Regards,
Team ECONDIR
<br>
<br>
<br>
</p>
                    </td>
                    </tr>
                </tbody>
            </table>
	   <table style="width: 563px; display: table; margin: auto;">
                <tbody>
                    <tr style="height: 21.5454px;">
                    <td style="padding: 30px 0px 30px 0px; text-align: center;">
                        <a href="" style="font-size: 25px;color: #135688; margin: 0px 10px 0px 0px;"><img src="http://dev17.onlinetestingserver.com/hn/econdir-wp/wp-content/themes/econ-dir/images/insta-icon.png"></a>

            	       <a href="" style="font-size: 25px;color: #3f5b98; margin: 0px 10px 0px 0px;"><img src="http://dev17.onlinetestingserver.com/hn/econdir-wp/wp-content/themes/econ-dir/images/fb-icon.png"></a>

            	       <a href="" style="font-size: 25px;color: #0873b2; margin: 0px 10px 0px 0px;"><img src="http://dev17.onlinetestingserver.com/hn/econdir-wp/wp-content/themes/econ-dir/images/linkedin-icon.png"></a>

                       <a href="" style="font-size: 25px;color: #22a0f2;"><img src="http://dev17.onlinetestingserver.com/hn/econdir-wp/wp-content/themes/econ-dir/images/twitter-icon.png"></a>
                       
                    </td>
                    </tr>
                </tbody>
            </table>

            <table style="width: 563px; display: table; margin: 0 auto 20px; background-color: #ff6712;">
                <tbody>
                    <tr>
                    <td>
                        <h3 style="font-size: 12px; font-weight:lighter; font-family: Gotham, Helvetica Neue, Helvetica, Arial, sans-serif, sans-serif; color: #fff; text-align: center;">Copyrights 2018, Econdir - All rights reserved.</h3>
                    </td>
                    </tr>
                </tbody>
            </table>

        </td>
        </tr>
    </tbody>
</table>', $headers);

	}elseif ($post->post_status == 'rejected') {
		
	$header = "MIME-Version: 1.0" . "\r\n";
	$header .= "Content-type:text/html;charset=UTF-8" . "\r\n";
	
		wp_mail( get_user_email_by_id($post->post_author),'ECONDIR | Profile Rejected', '<table style="width: 610px; background-color: #fff; display: table; margin: auto;">
	<tbody>
        <tr>
        <td>
            <table style="width: 563px; display: table; margin: 20px auto 0; background-color: #2a2a2a;">
                <tbody>
                    <tr>
                    <td style="width: 50%;  padding: 10px 0 10px 10px;"><a href="index.html"><img style="display: table; margin: 50px auto 50px;" src="http://dev17.onlinetestingserver.com/hn/econdir-wp/wp-content/themes/econ-dir/images/logo.png"></a></td>
                    </tr>
                </tbody>
            </table>

            <table style="width: 563px; display: table; margin: auto; background-color: #f2f2f2;">
                <tbody>
                    <tr>
                    <td style="padding: 70px 0px 70px 0;">
                    
                        <p style="font-size: 16px; color: #4d4d4d; font-family: Gotham, Helvetica Neue, Helvetica, Arial, sans-serif; text-align: center; padding: 0 50px 0 50px; margin: 0 0 0 0; line-height: 30px;">Dear User,<br>

                           Unfortunately, your profile has been rejected due to the following reason(s)
<br>
<br>

<Reason Field Data>
<br>
<br>

Best Regards,
Team ECONDIR <br>
<br>
<br>
 </p>
</td>
</tr>
</tbody>
            </table>
	   <table style="width: 563px; display: table; margin: auto;">
                <tbody>
                    <tr style="height: 21.5454px;">
                    <td style="padding: 30px 0px 30px 0px; text-align: center;">
                        <a href="" style="font-size: 25px;color: #135688; margin: 0px 10px 0px 0px;"><img src="http://dev17.onlinetestingserver.com/hn/econdir-wp/wp-content/themes/econ-dir/images/insta-icon.png"></a>

            	       <a href="" style="font-size: 25px;color: #3f5b98; margin: 0px 10px 0px 0px;"><img src="http://dev17.onlinetestingserver.com/hn/econdir-wp/wp-content/themes/econ-dir/images/fb-icon.png"></a>

            	       <a href="" style="font-size: 25px;color: #0873b2; margin: 0px 10px 0px 0px;"><img src="http://dev17.onlinetestingserver.com/hn/econdir-wp/wp-content/themes/econ-dir/images/linkedin-icon.png"></a>

                       <a href="" style="font-size: 25px;color: #22a0f2;"><img src="http://dev17.onlinetestingserver.com/hn/econdir-wp/wp-content/themes/econ-dir/images/twitter-icon.png"></a>
                       
                    </td>
                    </tr>
                </tbody>
            </table>

            <table style="width: 563px; display: table; margin: 0 auto 20px; background-color: #ff6712;">
                <tbody>
                    <tr>
                    <td>
                        <h3 style="font-size: 12px; font-weight:lighter; font-family: Gotham, Helvetica Neue, Helvetica, Arial, sans-serif, sans-serif; color: #fff; text-align: center;">Copyrights 2018, Econdir - All rights reserved.</h3>
                    </td>
                    </tr>
                </tbody>
            </table>

        </td>
        </tr>
    </tbody>
</table>', $header);
	}


	if (isset($_POST['company_name'])) {
		update_post_meta( $post_id, 'econdir_company_name', esc_attr( $_POST['company_name'] ) );
		update_post_meta( $post_id, 'company_location', esc_attr( $_POST['Location'] ) );
		update_post_meta( $post_id, 'econdir_company_phone', esc_attr( $_POST['company_phone'] ) );
		update_post_meta( $post_id, 'econdir_contact_person_name', esc_attr( $_POST['contact_person_name'] ) );
		update_post_meta( $post_id, 'econdir_city', esc_attr( $_POST['city'] ) );
		update_post_meta( $post_id, 'econdir_category', esc_attr( $_POST['category'] ) );
		update_post_meta( $post_id, 'econdir_subcats', esc_attr( $_POST['subcats'] ) );
		update_post_meta( $post_id, 'econdir_website', esc_attr( $_POST['website'] ) );
		update_post_meta( $post_id, 'company_email', esc_attr( $_POST['company_email'] ) );
	}



	if ( isset( $_POST['reason_for_cancellation__reason'] ) )
		update_post_meta( $post_id, 'reason_for_cancellation__reason', esc_attr( $_POST['reason_for_cancellation__reason'] ) );
}
add_action( 'save_post', 'reason_for_cancellation__save' );

/*
	Usage: reason_for_cancellation__get_meta( 'reason_for_cancellation__reason' )
*/



// Registering custom post status
function wpb_custom_post_status(){
	register_post_status('rejected', array(
		'label'                     => _x( 'Rejected', 'post' ),
		'public'                    => false,
		'exclude_from_search'       => false,
		'show_in_admin_all_list'    => true,
		'show_in_admin_status_list' => true,
		'label_count'               => _n_noop( 'Rejected <span class="count">(%s)</span>', 'Rejected <span class="count">(%s)</span>' ),
	) );
}
add_action( 'init', 'wpb_custom_post_status' );

// Using jQuery to add it to post status dropdown
add_action('admin_footer-post.php', 'wpb_append_post_status_list');
function wpb_append_post_status_list(){
	global $post;
	$complete = '';
	$label = '';
	if($post->post_type == 'directories'){
		if($post->post_status == 'rejected'){
			$complete = ' selected="selected"';
			$label = '<span id="post-status-display"> Rejected</span>';
		}
		echo '
		<script>
		jQuery(document).ready(function($){
			$("select#post_status").append("<option value=\"rejected\" '.$complete.'>Rejected</option>");
			$(".misc-pub-section label").append("'.$label.'");
			});
			</script>
			';
		}
	}

// Styling and scripts
add_action('lms_scripts', 'lms_scripts_styles');
function lms_scripts_styles(){
	echo '<link rel="stylesheet" href="'.get_template_directory_uri().'/inc/bootstrap.css">';
}


